config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',path_names: { sign_in: 'login',sign_out:'logout',sign_up:'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'angular-items', to: 'portfolios#angular'
  get 'rubyonrails-items', to: 'portfolios#rubyonrails'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :stories do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
has_many:technologies
accepts_nested_attributes_for :technologies, 
                reject_if: lambda {|attrs|attrs['name'].blank?}
                
include Placeholder

    validates_presence_of :title, :body, :main_image, :thumg_image

    #1st way to fing specific records with subtitle ANGULAR
    def self.angular
        where(subtitle:"Angular")
    end

    #2nd way to fing specific records with subtitle ANGULAR
    scope :ruby_on_rails_portfolios, ->{where(subtitle:"Ruby on Rails")}


    after_initialize :set_defaults

    def set_defaults
        self.main_image ||=Placeholder.image_generator(height:'600', width: '400')   
        self.thumg_image ||=Placeholder.image_generator(height:'350', width: '150')   
    end


end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"

  def index
    @portfolio = Portfolio.all
  end

  
  def angular
    @angular = Portfolio.angular
  end


  def rubyonrails
      @rubyonrails=Portfolio.ruby_on_rails_portfolios
  end

  def new
    @portfolio=Portfolio.new
    3.times {@portfolio.technologies.build}
  end


  def create
      @portfolio = Portfolio.new(portfolio_params)

      respond_to do |format|
        if @portfolio.save
          format.html { redirect_to portfolios_path, notice: "Your Portfolio is Live Now." }
          format.json { render :show, status: :created, location: @portfolio }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @portfolio.errors, status: :unprocessable_entity }
        end
      end
  end

  def edit
      @portfolio=Portfolio.find(params[:id])
  end

  def update
      @portfolio=Portfolio.find(params[:id])
      respond_to do |format|
        if @portfolio.update(portfolio_params)
          format.html { redirect_to portfolios_path, notice: "Portfolio was successfully updated." }
          format.json { render :show, status: :ok, location: @portfolio }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @portfolio.errors, status: :unprocessable_entity }
        end
      end
  end

  def destroy
      @portfolio=Portfolio.find(params[:id])
      @portfolio.destroy
      respond_to do |format|
        format.html { redirect_to portfolios_path, notice: "Your Portfolio is successfully destroyed." }
        format.json { head :no_content }
      end
  end

  


  def show
      @portfolio=Portfolio.find(params[:id])
  end


  private

      def portfolio_params
          params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
      end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Portfolio",new_portfolio_path %>


<% @angular.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
    <p><%= portfolio_item.subtitle%></p>
    <p><%= portfolio_item.body%></p>
    <%= image_tag portfolio_item.main_image if !portfolio_item.main_image.nil? %>
    <%= image_tag portfolio_item.thumg_image unless portfolio_item.thumg_image.nil? %><br>
    <%= link_to "Edit Portfolio",edit_portfolio_path(portfolio_item.id) %>
    <a href="/portfolios/<%= portfolio_item.id %>/edit">Edit Two</a>
    <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>

app/views/portfolios/edit.html.erb
<h1>Edit Your Portfolio Item</h1>


<%= form_for(@portfolio) do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle %>
    </div>
  
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Portfolio",new_portfolio_path %>


<% @portfolio.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
    <p><%= portfolio_item.subtitle%></p>
    <p><%= portfolio_item.body%></p>
    <%= image_tag portfolio_item.main_image if !portfolio_item.main_image.nil? %>
    <%= image_tag portfolio_item.thumg_image unless portfolio_item.thumg_image.nil? %><br>
    <%= link_to "Edit Portfolio",edit_portfolio_path(portfolio_item.id) %>
    <a href="/portfolios/<%= portfolio_item.id %>/edit">Edit Two</a>
    <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>


<%= form_for(@portfolio) do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle %>
    </div>
  
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>

    <ul>
      <%= form.fields_for :technologies do |technology_form| %>
        <li>
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name %>
        </li>
      <% end %>
    </ul>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/portfolios/rubyonrails.html.erb
<h1>Ruby on Rails Portfolio Items</h1>

<%= link_to "Create New Portfolio",new_portfolio_path %>


<% @rubyonrails.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
    <p><%= portfolio_item.subtitle%></p>
    <p><%= portfolio_item.body%></p>
    <%= image_tag portfolio_item.main_image if !portfolio_item.main_image.nil? %>
    <%= image_tag portfolio_item.thumg_image unless portfolio_item.thumg_image.nil? %><br>
    <%= link_to "Edit Portfolio",edit_portfolio_path(portfolio_item.id) %>
    <a href="/portfolios/<%= portfolio_item.id %>/edit">Edit Two</a>
    <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio.main_image %>

<h1><%= @portfolio.title %></h1>

<em><%= @portfolio.subtitle %></em>

<p><%= @portfolio.body %></>p


<h2> Technologies Used : </h2>

<% @portfolio.technologies.each do |t| %>
    <p><%= t.name%></p>
<% end %>